### PR TITLE
Bug 84

### LINKED ISSUE #84: Link db for User

### PR DESCRIPTION
**Pull request by zaccariach**
Fixes #84 

Link to db for a user already in db.

Need to jwt for new user

### CODE REVIEW

File: SQL-db/amt_pianorgue.sql [hunk 1]
```diff
@@ -12,7 +12,7 @@ CREATE TABLE IF NOT EXISTS `amt_pianorgue`.`article` (
   `price` DECIMAL(10,2) NULL DEFAULT NULL,
   `description` TEXT NOT NULL,
   `image` VARCHAR(255) NULL DEFAULT NULL,
-  `stock` INT UNSIGNED NOT NULL,
+  `stock` INT UNSIGNED NOT NULL,user
```
Comment (g-roch) [inline SQL-db/amt_pianorgue.sql:15]: Heur ??

File: application/src/main/java/com/amt/app/auth/User.java [hunk 2]
```diff
@@ -9,26 +9,32 @@
 public class User {
 
     @Getter
+    @Setter
```
Comment (g-roch) [inline application/src/main/java/com/amt/app/auth/User.java:12]: On n'a pas besoin de setter ?

**Review by g-roch — DISMISSED** [review]

**Review by g-roch — APPROVED** [review]
